name: Prevent pull request to main
on:
  workflow_call:
    inputs:
      example-input:
        description: "An example input"
        required: false
        type: string

jobs:
  check-branches:
    runs-on: self-hosted
    steps:
      - name: Check branches
        env:
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          GITHUB_BASE_REF: ${{ github.base_ref }}
        run: |
          if [ "$GITHUB_BASE_REF" != "main" ]; then
            echo "Create a pull request to main branch"
            exit 1
          fi
      -  uses: actions/checkout@v4
         with:
              repository: quic-viskum/checker-scripts
              path: checker-scripts
      - name: Chmod
        run: chmod +x ./checker-scripts/pylint_checker.sh
        
      - name: Run the checker
        run: ./checker-scripts/pylint_checker.sh
